name: bucketcheck
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_speed_dial: ^7.0.0
  #flutter_slidable: ^3.1.0
  intl: ^0.17.0 

  #Hive local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

  #Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter_launcher_icons:
  android: "launcher_icon" 
  image_path: "assets/images/icon/bucket_list.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon/bucket_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: InriaSans
      fonts:
      - asset: assets/fonts/InriaSans-Regular.ttf
